name: build-release
run-name: build-release
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install .
      - name: Build package
        shell: bash
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          OS=$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')
          pyinstaller builder.py modules/*.py \
            -n StaticGalleryBuilder-${VERSION}-${OS} \
            -F \
            --add-data files:files \
            --add-data templates:templates \
            --add-data themes:themes
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: StaticGalleryBuilder-${{ runner.os }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          generate_release_notes: true
          files: dist/**
